import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = resolve(root, "js/data-products-browser.js");

export async function browserBundle() {
  const result = await build({
    absWorkingDir: root,
    entryPoints: ["src/data-products/browser.js"],
    bundle: true,
    platform: "browser",
    format: "iife",
    target: "es2022",
    write: false,
    legalComments: "none",
    banner: { js: "// Generated by npm run build:browser. Edit src/data-products/ only.\n// Read-only: GET /v1/records only — never POST /v1/refresh." },
    plugins: [{
      name: "browser-fixture-adapter",
      setup(build) {
        build.onResolve({ filter: /^\.\/node-fixture\.ts$/ }, () => ({
          path: resolve(root, "src/data-products/browser-fixture.ts"),
        }));
      },
    }],
  });
  return result.outputFiles[0].text;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const generated = await browserBundle();
  if (process.argv.includes("--check")) {
    if (await readFile(outputPath, "utf8") !== generated) {
      console.error("Browser bundle is stale; run npm run build:browser and commit the output.");
      process.exitCode = 1;
    }
  } else {
    await writeFile(outputPath, generated);
  }
}
